# Site settings
title: Security and Securities
email: charles_barr@cambridgeprototyping.com
description: Charles Barr's personal blog. 
url: "http://charlesbarr.github.io" # the base hostname & protocol for your site
twitter_username: CapitalistChuck
github_username:  charlesbbarr

# Build settings
markdown: kramdown
